# Generated by Django 5.2.4 on 2025-07-09 14:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(max_length=4096)),
                ('sent_at', models.DateTimeField(auto_now_add=True, verbose_name='Sent at')),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rated_at', models.DateTimeField(auto_created=True, verbose_name='Rated At')),
                ('name', models.CharField(max_length=256)),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skillswap_common.skill')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('messages', models.ManyToManyField(to='skillswap_common.message')),
                ('ratings', models.ManyToManyField(to='skillswap_common.rating')),
                ('skills', models.ManyToManyField(to='skillswap_common.skill')),
            ],
        ),
        migrations.AddField(
            model_name='rating',
            name='rated_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skillswap_common.userprofile'),
        ),
        migrations.AddField(
            model_name='message',
            name='reciever',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='skillswap_common.userprofile'),
        ),
        migrations.AddField(
            model_name='message',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='skillswap_common.userprofile'),
        ),
    ]
