# Generated by Django 5.2.3 on 2025-07-11 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skillswap_common', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='description',
            field=models.TextField(max_length=4096),
        ),
        migrations.AlterField(
            model_name='skill',
            name='location',
            field=models.CharField(max_length=256),
        ),
    ]
