
# Generated by Django 5.2.4 on 2025-07-10 12:36


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [

        ("skillswap_common", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="skill",
            name="description",
            field=models.TextField(max_length=4096),
        ),
        migrations.AlterField(
            model_name="skill",
            name="location",
            field=models.CharField(max_length=256),
        ),
    ]
