# Generated by Django 5.2.4 on 2025-07-21 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skillswap_common', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='ratings',
            field=models.ManyToManyField(blank=True, to='skillswap_common.rating'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='skills',
            field=models.ManyToManyField(blank=True, to='skillswap_common.skill'),
        ),
    ]
