# Generated by Django 5.2.3 on 2025-07-15 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skillswap_common', '0002_alter_userprofile_user'),
        ('skillswap_common', '0002_category_remove_skill_skill_type_skill_created_at_and_more'),
    ]

    operations = [
    ]
