# Generated by Django 5.2.4 on 2025-07-14 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skillswap_common', '0002_alter_skill_description_alter_skill_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='bio',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='skills_needed',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='skills_offered',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.DeleteModel(
            name='Message',
        ),
    ]
