# Generated by Django 5.2.3 on 2025-07-15 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='skills_needed',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='skills_offered',
        ),
    ]
