# Generated by Django 5.2.3 on 2025-07-15 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skillswap_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='category',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='user',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Skill',
        ),
    ]
